Models/Racket.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace RacketManagement.Models
{
  public class Racket
  {
    public int RacketID { get; set; }
    [ForeignKey("Brand")]
    public int BrandID { get; set; }
    public int GripSizeID { get; set; }
    public int ModelID { get; set; }

    public Brand Brand { get; set; }
    public GripSize GripSize { get; set; }
    public Model Model { get; set; }
  }
}

Controllers/BrandController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RacketManagement.Data;
using RacketManagement.Models;

namespace RacketManagement.Controllers
{
    public class BrandController : Controller
    {
        private readonly RacketManagementContext _context;

        public BrandController(RacketManagementContext context)
        {
            _context = context;
        }

        // GET: Brand
        public async Task<IActionResult> Index()
        {
            return View(await _context.Brands.ToListAsync());
        }

        // GET: Brand/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var brand = await _context.Brands
                .FirstOrDefaultAsync(m => m.BrandID == id);
            if (brand == null)
            {
                return NotFound();
            }

            return View(brand);
        }

        // GET: Brand/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Brand/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BrandID,name")] Brand brand)
        {
            if (ModelState.IsValid)
            {
                _context.Add(brand);
                await _context.SaveChangesAsync();
                //return RedirectToAction(nameof(Index));
                return RedirectToAction("Create", "Racket", new { area = "" });
            }
            return View(brand);
        }

        // GET: Brand/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var brand = await _context.Brands.FindAsync(id);
            if (brand == null)
            {
                return NotFound();
            }
            return View(brand);
        }

        // POST: Brand/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BrandID,name")] Brand brand)
        {
            if (id != brand.BrandID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(brand);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BrandExists(brand.BrandID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(brand);
        }

        // GET: Brand/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var brand = await _context.Brands
                .FirstOrDefaultAsync(m => m.BrandID == id);
            if (brand == null)
            {
                return NotFound();
            }

            return View(brand);
        }

        // POST: Brand/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var brand = await _context.Brands.FindAsync(id);
            _context.Brands.Remove(brand);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BrandExists(int id)
        {
            return _context.Brands.Any(e => e.BrandID == id);
        }
    }
}

Controllers/GripSizeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RacketManagement.Data;
using RacketManagement.Models;

namespace RacketManagement.Controllers
{
    public class GripSizeController : Controller
    {
        private readonly RacketManagementContext _context;

        public GripSizeController(RacketManagementContext context)
        {
            _context = context;
        }

        // GET: GripSize
        public async Task<IActionResult> Index()
        {
            return View(await _context.GripSizes.ToListAsync());
        }

        // GET: GripSize/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gripSize = await _context.GripSizes
                .FirstOrDefaultAsync(m => m.GripSizeID == id);
            if (gripSize == null)
            {
                return NotFound();
            }

            return View(gripSize);
        }

        // GET: GripSize/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: GripSize/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("GripSizeID,size")] GripSize gripSize)
        {
            if (ModelState.IsValid)
            {
                _context.Add(gripSize);
                await _context.SaveChangesAsync();
                return RedirectToAction("Create", "Racket", new { area = "" });
            }
            return View(gripSize);
        }

        // GET: GripSize/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gripSize = await _context.GripSizes.FindAsync(id);
            if (gripSize == null)
            {
                return NotFound();
            }
            return View(gripSize);
        }

        // POST: GripSize/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("GripSizeID,size")] GripSize gripSize)
        {
            if (id != gripSize.GripSizeID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(gripSize);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GripSizeExists(gripSize.GripSizeID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(gripSize);
        }

        // GET: GripSize/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gripSize = await _context.GripSizes
                .FirstOrDefaultAsync(m => m.GripSizeID == id);
            if (gripSize == null)
            {
                return NotFound();
            }

            return View(gripSize);
        }

        // POST: GripSize/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var gripSize = await _context.GripSizes.FindAsync(id);
            _context.GripSizes.Remove(gripSize);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GripSizeExists(int id)
        {
            return _context.GripSizes.Any(e => e.GripSizeID == id);
        }
    }
}

Controllers/ModelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RacketManagement.Data;
using RacketManagement.Models;

namespace RacketManagement.Controllers
{
    public class ModelController : Controller
    {
        private readonly RacketManagementContext _context;

        public ModelController(RacketManagementContext context)
        {
            _context = context;
        }

        // GET: Model
        public async Task<IActionResult> Index()
        {
            return View(await _context.Models.ToListAsync());
        }

        // GET: Model/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var model = await _context.Models
                .FirstOrDefaultAsync(m => m.ModelID == id);
            if (model == null)
            {
                return NotFound();
            }

            return View(model);
        }

        // GET: Model/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Model/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ModelID,name")] Model model)
        {
            if (ModelState.IsValid)
            {
                _context.Add(model);
                await _context.SaveChangesAsync();
                return RedirectToAction("Create", "Racket", new { area = "" });
            }
            return View(model);
        }

        // GET: Model/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var model = await _context.Models.FindAsync(id);
            if (model == null)
            {
                return NotFound();
            }
            return View(model);
        }

        // POST: Model/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ModelID,name")] Model model)
        {
            if (id != model.ModelID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(model);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ModelExists(model.ModelID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        // GET: Model/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var model = await _context.Models
                .FirstOrDefaultAsync(m => m.ModelID == id);
            if (model == null)
            {
                return NotFound();
            }

            return View(model);
        }

        // POST: Model/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var model = await _context.Models.FindAsync(id);
            _context.Models.Remove(model);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ModelExists(int id)
        {
            return _context.Models.Any(e => e.ModelID == id);
        }
    }
}

Controllers/api/RacketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RacketManagement.Data;
using RacketManagement.Models;

namespace RacketManagement.Controllers.api
{
    [Route("api/[controller]")]
    [ApiController]
    public class RacketController : ControllerBase
    {
        private readonly RacketManagementContext _context;

        public RacketController(RacketManagementContext context)
        {
            _context = context;
        }

        // GET: api/Racket
        [HttpGet]
        public async Task<ActionResult<IEnumerable<Racket>>> GetRackets()
        {
            return await _context.Rackets.ToListAsync();
        }

        // GET: api/Racket/5
        [HttpGet("{id}")]
        public async Task<ActionResult<Racket>> GetRacket(int id)
        {
            var racket = await _context.Rackets.FindAsync(id);

            if (racket == null)
            {
                return NotFound();
            }

            return racket;
        }

        // PUT: api/Racket/5
        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
        [HttpPut("{id}")]
        public async Task<IActionResult> PutRacket(int id, Racket racket)
        {
            if (id != racket.RacketID)
            {
                return BadRequest();
            }

            _context.Entry(racket).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!RacketExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

        // POST: api/Racket
        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
        [HttpPost]
        public async Task<ActionResult<Racket>> PostRacket(Racket racket)
        {
            _context.Rackets.Add(racket);
            await _context.SaveChangesAsync();

            return CreatedAtAction("GetRacket", new { id = racket.RacketID }, racket);
        }

        // DELETE: api/Racket/5
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteRacket(int id)
        {
            var racket = await _context.Rackets.FindAsync(id);
            if (racket == null)
            {
                return NotFound();
            }

            _context.Rackets.Remove(racket);
            await _context.SaveChangesAsync();

            return NoContent();
        }

        private bool RacketExists(int id)
        {
            return _context.Rackets.Any(e => e.RacketID == id);
        }
    }
}

Views/Racket/Create.cshtml
@model RacketManagement.Models.Racket

@{
    ViewData["Title"] = "Create";
}

<h1>Racket</h1>

<hr />

<form asp-action="Create">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <table class="table">
        <tbody>
            <tr>
                <td class="col-md-2">
                    <div class="form-group">
                        <select asp-for="BrandID" class ="form-control" asp-items="ViewBag.BrandName"></select>
                    </div>
                </td>
                <td class="col-md-8"></td>
                <td class="col-md-2">
                    <button type="button" class="btn btn-secondary">
                        <a class="text-light" style="text-decoration: none"  asp-controller="Brand" asp-action="Create">New Brand</a>
                    </button>
                </td>
            </tr>
            <tr>
                <td class="col-md-2">
                    <div class="form-group">
                        <select asp-for="ModelID" class ="form-control" asp-items="ViewBag.ModelName"></select>
                    </div>
                </td>
                <td class="col-md-8"></td>
                <td class="col-md-2">
                    <button type="button" class="btn btn-secondary">
                        <a class="text-light" style="text-decoration: none"  asp-controller="Model" asp-action="Create">New Model</a>
                    </button>
                </td>
            </tr>
            <tr>
                <td class="col-md-2">
                    <div class="form-group">
                        <select asp-for="GripSizeID" class ="form-control" asp-items="ViewBag.Gripsize"></select>
                    </div>
                </td>
                <td class="col-md-8"></td>
                <td class="col-md-2">
                    <button type="button" class="btn btn-secondary">
                        <a class="text-light" style="text-decoration: none"  asp-controller="GripSize" asp-action="Create">New Gripsize</a>
                    </button>
                </td>
            </tr>                
        </tbody>
    </table>
    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary" />
    </div>
</form>

Views/Racket/Delete.cshtml
@model RacketManagement.Models.Racket

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Racket</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Brand)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Brand.BrandID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GripSize)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GripSize.GripSizeID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Model)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Model.ModelID)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="RacketID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Racket/Details.cshtml
@model RacketManagement.Models.Racket

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Racket</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Brand)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Brand.BrandID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GripSize)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GripSize.GripSizeID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Model)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Model.ModelID)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.RacketID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Racket/Edit.cshtml
@model RacketManagement.Models.Racket

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Racket</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="RacketID" />
            <div class="form-group">
                <label asp-for="BrandID" class="control-label"></label>
                <select asp-for="BrandID" class="form-control" asp-items="ViewBag.BrandName"></select>
                <span asp-validation-for="BrandID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModelID" class="control-label"></label>
                <select asp-for="ModelID" class="form-control" asp-items="ViewBag.ModelName"></select>
                <span asp-validation-for="ModelID" class="text-danger"></span>
            </div>
            <div class="form-group" style="padding-bottom: 7px">
                <label asp-for="GripSizeID" class="control-label"></label>
                <select asp-for="GripSizeID" class="form-control" asp-items="ViewBag.Gripsize"></select>
                <span asp-validation-for="GripSizeID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

Views/Racket/Index.cshtml
@model IEnumerable<RacketManagement.Models.Racket>

@{
    ViewData["Title"] = "Racket";
}

<h1>Rackets</h1>

@if (User.Identity.IsAuthenticated)
{
    if(User.IsInRole("Administrator"))
    {
        <button type="button" class="btn btn-primary">
            <a asp-action="Create" class="text-light" style="text-decoration: none">Create</a>
        </button>
    }
}

<table class="table">
    <thead>
        <tr>
            <th>Racket</th>
            @if (User.Identity.IsAuthenticated)
            {
                if(User.IsInRole("Administrator"))
                {
                    <th></th>
                }
            }
        </tr>
    </thead>
    <tbody>
    @foreach (var item in Model) {
        <tr>
            <td>
                @item.Brand.name @item.Model.name @item.GripSize.size
            </td>
            @if (User.Identity.IsAuthenticated)
            {
                if(User.IsInRole("Administrator"))
                {
                    <td>
                        <a class="text-light" style="text-decoration: none" asp-action="Edit" asp-route-id="@item.RacketID">
                            <button type="button" class="btn btn-secondary btn-sm">Edit</button>
                        </a>
                        <a class="text-light" style="text-decoration: none" asp-action="Delete" asp-route-id="@item.RacketID">
                            <button type="button" class="btn btn-secondary btn-sm">Delete</button>
                        </a>
                    </td>
                }
            }
        </tr>
    }
    </tbody>
</table>